# Gather hardware info and write to hardware-config.md
param(
    [string]$OutputFile = (Join-Path $PSScriptRoot "..\hardware-config.md")
)

$cpu = Get-CimInstance Win32_Processor | Select-Object -First 1
$ram = Get-CimInstance Win32_ComputerSystem
$os = Get-CimInstance Win32_OperatingSystem

$totalRamGB = [math]::Round($ram.TotalPhysicalMemory / 1GB, 1)

# Get GPU info: prefer nvidia-smi for NVIDIA (WMI AdapterRAM is often wrong on laptops),
# fall back to WMI for non-NVIDIA or if nvidia-smi unavailable
$gpuEntries = @()
$nvidiaSmi = Get-Command nvidia-smi -ErrorAction SilentlyContinue

if ($nvidiaSmi) {
    $nvidiaOutput = & nvidia-smi --query-gpu=name,memory.total --format=csv,noheader 2>&1
    if ($LASTEXITCODE -eq 0) {
        foreach ($line in $nvidiaOutput) {
            if ($line -match '^(.+),\s*(\d+)\s*MiB') {
                $gpuName = $Matches[1].Trim()
                $vramMB = [int]$Matches[2]
                $vramGB = [math]::Round($vramMB / 1024, 1)
                $gpuEntries += @{ Name = $gpuName; VRAM_GB = $vramGB; VRAM_Bytes = $vramMB * 1MB }
            }
        }
    }
}

# Fallback: WMI for any GPU not found via nvidia-smi (e.g., AMD, Intel Arc)
$wmiGpus = Get-CimInstance Win32_VideoController | Where-Object {
    $_.AdapterRAM -gt 0 -and $_.Name -notmatch 'Virtual|Sharing|Remote|GameViewer|Citrix|Indirect'
}
foreach ($g in $wmiGpus) {
    $alreadyFound = $gpuEntries | Where-Object { $g.Name -match [regex]::Escape($_.Name.Split(' ')[0..2] -join ' ') }
    if (-not $alreadyFound) {
        $vramGB = [math]::Round($g.AdapterRAM / 1GB, 1)
        $gpuEntries += @{ Name = $g.Name; VRAM_GB = $vramGB; VRAM_Bytes = $g.AdapterRAM }
    }
}

$gpuLines = foreach ($g in $gpuEntries) {
    "| **GPU** | $($g.Name) |`n| **VRAM** | $($g.VRAM_GB) GB |"
}

$maxVramGB = if ($gpuEntries.Count -gt 0) { ($gpuEntries | ForEach-Object { $_.VRAM_GB } | Measure-Object -Maximum).Maximum } else { 0 }

@"
# Hardware Configuration

> Auto-generated by `scripts/hardware-info.ps1`. Last updated: $(Get-Date -Format 'yyyy-MM-dd')

| Component | Detail |
|-----------|--------|
| **CPU** | $($cpu.Name) |
| **CPU Cores** | $($cpu.NumberOfCores) cores / $($cpu.NumberOfLogicalProcessors) logical |
| **RAM** | $totalRamGB GB |
$($gpuLines -join "`n")
| **OS** | $($os.Caption) |

## Model Size Guidance

Based on available VRAM ($maxVramGB GB) and system RAM ($totalRamGB GB):

- **GPU-only (fast):** Models up to ~$([math]::Floor($maxVramGB * 0.8)) GB
- **GPU+CPU hybrid:** Models up to ~$([math]::Floor($maxVramGB * 1.5)) GB at reduced speed
- **CPU-only (slow):** Models up to ~$([math]::Floor($totalRamGB * 0.6)) GB
- **Max recommended:** ~$([math]::Floor($totalRamGB * 0.3)) GB model
"@ | Out-File -FilePath $OutputFile -Encoding UTF8 -NoNewline

Write-Host "Hardware config written to: $OutputFile"
