# Gather Ollama model info and write to local-models.md
param(
    [string]$OutputFile = (Join-Path $PSScriptRoot "..\local-models.md")
)

$models = ollama list 2>&1
if ($LASTEXITCODE -ne 0) {
    Write-Host "Failed to get model list: $models"
    exit 1
}

# Parse model list (skip header line)
$modelLines = $models | Select-Object -Skip 1 | Where-Object { $_.Trim() -ne '' }

$modelEntries = @()
foreach ($line in $modelLines) {
    $parts = $line -split '\s{2,}'
    if ($parts.Count -ge 2) {
        $modelEntries += @{
            Name = $parts[0].Trim()
            Size = $parts[2].Trim()
        }
    }
}

# Get detailed info for each model
$modelDetails = @()
foreach ($m in $modelEntries) {
    $info = ollama show $m.Name 2>&1 | Out-String
    $modelDetails += @{
        Name = $m.Name
        Size = $m.Size
        Info = $info
    }
}

# Build markdown
$date = Get-Date -Format 'yyyy-MM-dd'

$md = @"
# Local Ollama Models

> Auto-generated by `scripts/model-info.ps1`. Last updated: $date

## Available Models

"@

foreach ($m in $modelDetails) {
    $name = $m.Name
    $size = $m.Size
    $info = $m.Info

    # Try to extract model family for basic categorization
    $isMultimodal = $name -match 'llava|bakllava|minicpm|cogvlm'
    $isEmbedding = $name -match 'embed|nomic'
    $isReasoning = $name -match 'deepseek-r1|qwq'

    $type = if ($isEmbedding) { "Embedding" }
            elseif ($isMultimodal) { "Multimodal (Vision + Text)" }
            elseif ($isReasoning) { "Reasoning (Chain-of-Thought)" }
            else { "Text Generation" }

    $capabilities = if ($isMultimodal) { "OCR, image description, visual Q&A, document understanding" }
                    elseif ($isEmbedding) { "Text embeddings for semantic search, clustering, RAG" }
                    elseif ($isReasoning) { "Step-by-step reasoning, math, logic, problem-solving" }
                    else { "General chat, coding, text processing" }

    $bestFor = if ($isMultimodal) { "图文识别、图片内容提取、图表理解" }
               elseif ($isEmbedding) { "文本向量化、语义搜索、RAG 检索" }
               elseif ($isReasoning) { "数学推理、逻辑问题、复杂分析" }
               else { "通用对话、代码生成、文本处理" }

    $apiExample = if ($isEmbedding) {
        "curl http://localhost:11434/api/embeddings -d '{\"model\":\"$name\",\"prompt\":\"Text to embed\"}'"
    } else {
        "curl http://localhost:11434/api/generate -d '{\"model\":\"$name\",\"prompt\":\"Your prompt here\"}'"
    }

    $escapedInfo = $info -replace '`', '\`' -replace '\$', '`$'

    $md += @"

### $name ($size)
- **Type:** $type
- **Capabilities:** $capabilities
- **Best for:** $bestFor
- **API Usage:**
  ```bash
  $apiExample
  ```

<details>
<summary>Model Details (ollama show)</summary>

```
$escapedInfo
```

</details>

"@
}

# Task mapping table
$hasMultimodal = ($modelDetails | Where-Object { $_.Name -match 'llava|bakllava|minicpm|cogvlm' }).Count -gt 0
$hasReasoning = ($modelDetails | Where-Object { $_.Name -match 'deepseek-r1|qwq' }).Count -gt 0
$hasEmbedding = ($modelDetails | Where-Object { $_.Name -match 'embed|nomic' }).Count -gt 0
$textModels = ($modelDetails | Where-Object { $_.Name -notmatch 'llava|bakllava|minicpm|cogvlm|embed|nomic|deepseek-r1|qwq' })
$reasoningModels = ($modelDetails | Where-Object { $_.Name -match 'deepseek-r1|qwq' })

$md += @"

## Task → Model Mapping

| Task | Recommended Model |
|------|-------------------|
"@

if ($hasMultimodal) {
    $md += "| OCR / 图文识别 | llava-llama3 / multimodal model |`n"
    $md += "| Image description | llava-llama3 / multimodal model |`n"
    $md += "| Document analysis | llava-llama3 / multimodal model |`n"
}

if ($textModels.Count -gt 0) {
    $fastModel = ($textModels | Sort-Object { [double]($_.Size -replace '[^0-9.]', '') } | Select-Object -First 1)
    $qualityModel = ($textModels | Sort-Object { [double]($_.Size -replace '[^0-9.]', '') } -Descending | Select-Object -First 1)
    if ($fastModel) { $md += "| General chat (fast) | $($fastModel.Name) |`n" }
    if ($qualityModel -and $qualityModel.Name -ne $fastModel.Name) { $md += "| General chat (quality) | $($qualityModel.Name) |`n" }
    $md += "| Coding | qwen / deepseek model |`n"
}

if ($reasoningModels.Count -gt 0) {
    $md += "| Math / Logic | $($reasoningModels[0].Name) |`n"
}

$md += "| Chinese tasks | qwen model |`n"

if ($hasEmbedding) {
    $md += "| Embeddings / RAG | nomic-embed-text |`n"
}

$md | Out-File -FilePath $OutputFile -Encoding UTF8 -NoNewline

Write-Host "Model info written to: $OutputFile"
